name: LTCN_SR_x4_v3_MIRB
model_type: SRModel
scale: 4 # 2/3/4/8
num_gpu: 1 # or 4
manual_seed: 10

datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
#    dataroot_gt: E:\Dataset\train\DIV2K\DIV2K_train_HR_sub.lmdb
#    dataroot_lq: E:\Dataset\train\DIV2K\DIV2K_train_LR_bicubic_X2_sub.lmdb
    dataroot_gt:  D:\Dataset\DIV2K\train\DIV2K_train_HR_sub
    dataroot_lq:  D:\Dataset\DIV2K\train\DIV2K_train_LR_bicubic_X4_sub
    # meta_info_file: hat/data/meta_info/meta_info_DF2Ksub_GT.txt
    io_backend:
      type: disk

    gt_size: 128 #scale*48 or scale*64
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true # true

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: E:\Dataset\test\Set5\HR
    dataroot_lq: E:\Dataset\test\Set5\LR_bicubic\X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

  # val_2:
  #   name: Set14
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/Set14/GTmod2
  #   dataroot_lq: ./datasets/Set14/LRbicx2
  #   io_backend:
  #     type: disk

  # val_3:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/urban100/GTmod2
  #   dataroot_lq: ./datasets/urban100/LRbicx2
  #   io_backend:
  #     type: disk


# network structures
network_g:
  type: LTCN
  scale: 4 #or 3/4
  int_channels: 3
  out_channels: 3
  n_resblocks: 4 # 5 for MAN-tiny; 24 for MAN-light; 36 for MAN
  n_resgroups: 1
  n_feats: 40 # 48 for MAN-tiny; 60 for MAN-light; 180 for MAN
  ffn_expansion_factor: 2.66


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 10e-4 # 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [800000, 1200000, 140000, 1500000]
    gamma: 0.5

    #type: CosineAnnealingRestartLR
    #periods: [1600000]
    #restart_weights: [1]
    #eta_min: !!float 1e-7

  total_iter: 1600000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4 # 2/3/4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4 # 2/3/4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
